#!/bin/bash
set -e

# Elastic
service elasticsearch start
chmod +x /usr/share/oc-search-elastic/put_template.sh
/usr/share/oc-search-elastic/put_template.sh

# Search Api
chown -R elasticsearch:elasticsearch /var/lib/oc-search-elastic/
chmod 700 /var/lib/oc-search-elastic/oc-search-elastic.jar

systemctl enable oc-search-elastic.service
service oc-search-elastic start