#!/bin/bash
set -e

# Elastic
service elasticsearch start
chmod +x /usr/share/oc-search-elastic/put_template.sh
/usr/share/oc-search-elastic/put_template.sh

# Search Api
ln -sf /etc/oc-search-elastic/application.properties /var/lib/oc-search-elastic/application.properties
systemctl enable oc-search-elastic.service
service oc-search-elastic start